#!/usr/bin/env python
"""
awsd - movement
space - jump
mouse - look around
"""
import numpy as np
import os

import direct.directbase.DirectStart
from pandac.PandaModules import *
from direct.gui.OnscreenText import OnscreenText
import sys

floorraise = 0.01 # step every smaller scene up by a tiny amount to make floors separate
x_separation = 50
scale_level_of_1m_world = 3

def scene_scale_from_scale_level(scale_level):
    """ 0: 1000, 1: 100, 2: 10, 3: 1, 4: 0.1, ... """
    return np.power(0.1, scale_level-scale_level_of_1m_world)

def floorz_from_scale_level(scale_level):
    if scale_level < 0:
        return 0
    else:
        scene_scale = scene_scale_from_scale_level(scale_level)
        return floorz_from_scale_level(scale_level - 1) + scale_level * floorraise * scene_scale

class FPS(object):
    """
        This is a very simple FPS like -
         a building block of any game i guess
    """
    current_folder = ['/', 'home', 'daniel']
    in_cutscene = None
    parent_room_node = None
    siblings_room_nodes = {}
    children_room_nodes = {}

    def __init__(self):
        """ create a FPS type game """
        self.init_collision()
        self.scaletext = OnscreenText(text="Fileworld", style=1, fg=(1,1,1,1),
                    pos=(1.3,-0.95), align=TextNode.ARight, scale = .07)
        OnscreenText(text=__doc__, style=1, fg=(1,1,1,1),
            pos=(-1.3, 0.95), align=TextNode.ALeft, scale = .05)
        self.load_level()
        self.init_player()
        base.accept( "escape" , sys.exit)
        base.accept( "arrow_up" , self.scale_player_up)
        base.accept( "arrow_down" , self.scale_player_down)
        base.disableMouse()

        # hide mouse cursor, comment these 3 lines to see the cursor
        props = WindowProperties()
        props.setCursorHidden(True)
        base.win.requestProperties(props)

        # init game loop task
        taskMgr.add(self.game_loop, 'gameloop-task')


    def init_collision(self):
        """ create the collision system """
        base.cTrav = CollisionTraverser()
        base.pusher = CollisionHandlerPusher()

    def regen_scenes_for_current_folder(self):
        # delete previous
        if self.parent_room_node is not None:
            self.parent_room_node.removeNode()
        for c, v in self.siblings_room_nodes.items():
            v.removeNode()
        for c, v in self.children_room_nodes.items():
            v.removeNode()

        # create parent room scene (larger)
        if len(self.current_folder) == 1:
            # can't create parent, as there is nothing above '/'
            z_offset = - floorraise
            self.parent_room_node = loader.loadModel('models/environment')
            self.parent_room_node.reparentTo(render)
            self.parent_room_node.setTwoSided(True)
            self.parent_room_node.setScale(self.parent_scale, self.parent_scale, self.parent_scale)
            self.parent_room_node.setPos(0, 0, z_offset - 1)
        else:
            c = self.current_folder[-2]
            z_offset = - floorraise
            self.parent_room_node = loader.loadModel('house.bam')
            self.parent_room_node.reparentTo(render)
            self.parent_room_node.setTwoSided(True)
            self.parent_room_node.setScale(self.parent_scale, self.parent_scale, self.parent_scale)
            self.parent_room_node.setPos(0, 0, z_offset)
            text = TextNode(c)
            text.setText(c)
            text3d = NodePath(text)
            text3d.reparentTo(self.parent_room_node)
            text3d.setScale(-1,1,1)
            text3d.setPos(0,11,5)
            text3d.setTwoSided(True)

        # sibling room scenes (children of parent)
        # current room is one of those (I am the child of my parents)
        if len(self.current_folder) == 1:
            siblings = [self.current_folder[-1]]
        else:
            parentdir = '/'.join(self.current_folder[:-1])
            siblingdirs = [f.name for f in os.scandir(parentdir) if f.is_dir()]
            siblings = siblingdirs[:3]
            if len(siblings) >= 2 and self.current_folder[-1] not in siblings:
                siblings[1] = self.current_folder[-1]
        self.siblings_room_nodes = {c: None for c in siblings}
        for i, c in enumerate(siblings):
            scale = self.siblings_scale
            z_offset = 0
            x_separation_index = i - len(siblings) // 2
            self.siblings_room_nodes[c] = loader.loadModel('house.bam')
            self.siblings_room_nodes[c].reparentTo(render)
            self.siblings_room_nodes[c].setTwoSided(True)
            self.siblings_room_nodes[c].setScale(scale, scale, scale)
            self.siblings_room_nodes[c].setPos(scale * x_separation* x_separation_index, 0, z_offset)
            text = TextNode(c)
            text.setText(c)
            text3d = NodePath(text)
            text3d.reparentTo(self.siblings_room_nodes[c])
            text3d.setScale(-1,1,1)
            text3d.setPos(0,11,5)
            text3d.setTwoSided(True)

        # child room scenes, smaller
        currentdir = '/'.join(self.current_folder)
        childrendir = [f.name for f in os.scandir(currentdir) if f.is_dir()]
        children = childrendir[:3]
        self.children_room_nodes = {c: None for c in children}
        for i, c in enumerate(children):
            scale = self.children_scale
            z_offset = + floorraise
            x_separation_index = i - len(children) // 2
            self.children_room_nodes[c] = loader.loadModel('house.bam')
            self.children_room_nodes[c].reparentTo(render)
            self.children_room_nodes[c].setTwoSided(True)
            self.children_room_nodes[c].setScale(scale, scale, scale)
            self.children_room_nodes[c].setPos(scale * x_separation* x_separation_index, 0, z_offset)
            text = TextNode(c)
            text.setText(c)
            text3d = NodePath(text)
            text3d.reparentTo(self.children_room_nodes[c])
            text3d.setScale(-1,1,1)
            text3d.setPos(0,11,5)
            text3d.setTwoSided(True)

        self.scaletext.setText('/'.join(self.current_folder)[1:])

    def load_level(self):
        """ load the self.level
            must have
            <Group> *something* {
              <Collide> { Polyset keep descend }
            in the egg file
        """
        self.scenes = [None for i in range(20)]


        self.parent_scale = 10.
        self.siblings_scale = 1.
        self.children_scale = 0.1

        self.regen_scenes_for_current_folder()


        ambientLight = AmbientLight('ambientLight')
        ambientLight.setColor((0.3, 0.3, 0.3, 1))
        ambientLightNP = render.attachNewNode(ambientLight)
        render.setLight(ambientLightNP)
        render.set_shader_auto()

        # light
        ambientLight = AmbientLight('ambientLight')
        ambientLight.setColor((0.3, 0.3, 0.3, 1))
        ambientLightNP = render.attachNewNode(ambientLight)
        render.setLight(ambientLightNP)
        render.set_shader_auto()

    def init_player(self):
        """ loads the player and creates all the controls for him"""
        self.player = Player()

    def get_current_room_depth(self):
        return len(self.current_folder)

    def scale_player_down(self):
        if len(list(self.children_room_nodes.keys())) >= 2:
            child_to_enter = list(self.children_room_nodes.keys())[1]
        else:
            child_to_enter = list(self.children_room_nodes.keys())[0]
        player_pos = self.player.node.getPos()
        self.in_cutscene = {"name": "scale_down", "t0_player_pos": player_pos, "child_to_enter": child_to_enter, "t": 0, "duration": 1}

    def scale_player_up(self):
        player_pos = self.player.node.getPos()
        self.in_cutscene = {"name": "scale_up", "t0_player_pos": player_pos, "t": 0, "duration": 1}

    def cutscene_update(self):
        if self.in_cutscene["name"] == "scale_up":
            t0_player_pos = self.in_cutscene["t0_player_pos"]
            T = self.in_cutscene["duration"]
            t = self.in_cutscene["t"]
            # scale factor (1 to 0.1)
            s0 = 1.
            sT = 0.1
            s = s0 * (1. - t/T) + sT * t/T
            # parents shrink to one of siblings (later add siblings)
            self.parent_room_node.setScale(self.parent_scale * s, self.parent_scale * s, self.parent_scale * s)
            # siblings shrink to children
            for i, scene in enumerate(self.siblings_room_nodes.values()):
                z_offset = +floorraise
                x_separation_index = i - len(self.siblings_room_nodes.values()) // 2
                scene.setScale(self.siblings_scale * s, self.siblings_scale * s, self.siblings_scale * s)
                scene.setPos(self.siblings_scale * s * x_separation * x_separation_index, 0, z_offset)
            # children shrink to grandchildren
            for i, scene in enumerate(self.children_room_nodes.values()):
                z_offset = 0
                x_separation_index = i - len(self.children_room_nodes.values()) // 2
                scene.setScale(self.children_scale * s, self.children_scale * s, self.children_scale * s)
                scene.setPos(self.children_scale * s * x_separation * x_separation_index, 0, z_offset)
            # scale player position in world
            t_player_pos = t0_player_pos * s
            self.player.node.setPos(t_player_pos[0], t_player_pos[1], t0_player_pos[2])
            t += globalClock.getDt()
            self.in_cutscene["t"] = t
            if t >= T:
                self.in_cutscene = None
                self.current_folder.pop(-1)
                self.regen_scenes_for_current_folder()
                return
        elif self.in_cutscene["name"] == "scale_down":
            t0_player_pos = self.in_cutscene["t0_player_pos"]
            T = self.in_cutscene["duration"]
            t = self.in_cutscene["t"]
            # scale factor (1 to 0.1)
            s0 = 1.
            sT = 10.
            s = s0 * (1. - t/T) + sT * t/T
            # parents become grandparents (later disappear)
            self.parent_room_node.setScale(self.parent_scale * s, self.parent_scale * s, self.parent_scale * s)
            # siblings become parents
            for i, scene in enumerate(self.siblings_room_nodes.values()):
                z_offset = -floorraise
                x_separation_index = i - len(self.siblings_room_nodes.values()) // 2
                scene.setScale(self.siblings_scale * s, self.siblings_scale * s, self.siblings_scale * s)
                scene.setPos(self.siblings_scale * s * x_separation * x_separation_index, 0, z_offset)
            # children become siblings
            for i, scene in enumerate(self.children_room_nodes.values()):
                z_offset = 0
                x_separation_index = i - len(self.children_room_nodes.values()) // 2
                scene.setScale(self.children_scale * s, self.children_scale * s, self.children_scale * s)
                scene.setPos(self.children_scale * s * x_separation * x_separation_index, 0, z_offset)
            # scale player position in world
            t_player_pos = t0_player_pos * s
            self.player.node.setPos(t_player_pos[0], t_player_pos[1], t0_player_pos[2])
            t += globalClock.getDt()
            self.in_cutscene["t"] = t
            if t >= T:
                self.current_folder.append(self.in_cutscene["child_to_enter"])
                self.in_cutscene = None
                self.regen_scenes_for_current_folder()
                return

    def game_loop(self, task):
        self.player.mouseUpdate()
        if self.in_cutscene is None:
            self.player.moveUpdate()
            self.player.jumpUpdate()
        else:
            self.cutscene_update()
        return task.cont


class Player(object):
    """
        Player is the main actor in the fps game
    """
    speed = 50
    height = 1.8
    initialjumpvel = 5
    FORWARD = Vec3(0,2,0)
    BACK = Vec3(0,-1,0)
    LEFT = Vec3(-1,0,0)
    RIGHT = Vec3(1,0,0)
    STOP = Vec3(0)
    walk = STOP
    strafe = STOP
    boost = 1
    readyToJump = False
    zvel = 0
    terminalzvel = -10
    gravity = -10
    lensneardist = 1

    def __init__(self):
        """ inits the player """
        self.loadModel()
        self.setUpCamera()
        self.createCollisions()
        self.attachControls()

    def loadModel(self):
        """ make the nodepath for player """
        self.node = NodePath('player')
        self.node.reparentTo(render)
        self.node.setPos(0,5,5)
        self.node.setScale(.05)

    def setUpCamera(self):
        """ puts camera at the players node """
        pl =  base.cam.node().getLens()
        pl.setFov(70)
        base.cam.node().setLens(pl)
        base.camera.reparentTo(self.node)

    def createCollisions(self):
        """ create a collision solid and ray for the player """
        cn = CollisionNode('player')
#         cn.addSolid(CollisionSphere(0,0,0,3))
        solid = self.node.attachNewNode(cn)
        base.cTrav.addCollider(solid,base.pusher)
        base.pusher.addCollider(solid,self.node, base.drive.node())
        # init players floor collisions
        ray = CollisionRay()
        ray.setOrigin(0,0,0)
        ray.setDirection(0,0,-1)
        cn = CollisionNode('playerRay')
        cn.addSolid(ray)
        cn.setFromCollideMask(BitMask32.bit(0))
        cn.setIntoCollideMask(BitMask32.allOff())
        solid = self.node.attachNewNode(cn)
        self.nodeGroundHandler = CollisionHandlerQueue()
        base.cTrav.addCollider(solid, self.nodeGroundHandler)

    def attachControls(self):
        """ attach key events """
        base.accept( "space" , self.__setattr__,["readyToJump",True])
        base.accept( "space-up" , self.__setattr__,["readyToJump",False])
        base.accept( "s" , self.__setattr__,["walk",self.STOP] )
        base.accept( "w" , self.__setattr__,["walk",self.FORWARD])
        base.accept( "s" , self.__setattr__,["walk",self.BACK] )
        base.accept( "s-up" , self.__setattr__,["walk",self.STOP] )
        base.accept( "w-up" , self.__setattr__,["walk",self.STOP] )
        base.accept( "a" , self.__setattr__,["strafe",self.LEFT])
        base.accept( "d" , self.__setattr__,["strafe",self.RIGHT] )
        base.accept( "a-up" , self.__setattr__,["strafe",self.STOP] )
        base.accept( "d-up" , self.__setattr__,["strafe",self.STOP] )
        base.accept( "lshift-up" , self.__setattr__,["boost",1] )
        base.accept( "lshift" , self.__setattr__,["boost",2] )

    def mouseUpdate(self):
        """ this task updates the mouse """
        md = base.win.getPointer(0)
        x = md.getX()
        y = md.getY()
        if base.win.movePointer(0, base.win.getXSize()//2, base.win.getYSize()//2):
            self.node.setH(self.node.getH() -  (x - base.win.getXSize()//2)*0.1)
            base.camera.setP(base.camera.getP() - (y - base.win.getYSize()//2)*0.1)

    def moveUpdate(self):
        """ this task makes the player move """
        # move where the keys set it
        self.node.setPos(self.node,self.walk*globalClock.getDt()*self.speed*self.boost)
        self.node.setPos(self.node,self.strafe*globalClock.getDt()*self.speed)

    def jumpUpdate(self):
        """ this task simulates gravity and makes the player jump """
        # get the highest Z from the down casting ray
        floorZ = -100
        for i in range(self.nodeGroundHandler.getNumEntries()):
            entry = self.nodeGroundHandler.getEntry(i)
            z = entry.getSurfacePoint(render).getZ()
            if z > floorZ and entry.getIntoNode().getName() != "player":
                floorZ = z
        floorZ = 0
        floorPadding = self.height * 0.1
        feetZ = self.node.getZ() - self.height
        # feet above padded ground (floating)
        if floorZ + floorPadding < feetZ:
            # apply gravity
            if self.zvel > self.terminalzvel:
                self.zvel = self.zvel + self.gravity * globalClock.getDt()
        # feet below ground ->
        if floorZ > feetZ:
            self.zvel = 0
            self.node.setZ(floorZ+self.height)
        # feet below paddedground
        if floorZ + floorPadding > feetZ:
            # enable jump again
            if self.readyToJump:
#                 self.node.setZ(floorZ+floorPadding)
                self.zvel = self.initialjumpvel
        print("{:.2f}, {:.2f}, {:.2f}, {:.2f}, {:.2f}".format(
            self.node.getZ(), self.height, feetZ, floorZ, self.zvel))
        # apply velocity
        self.node.setZ(self.node.getZ()+self.zvel*globalClock.getDt())

FPS()
run()
